---
title: "Publications"
---

## In preparation

Ott, C., Rebuschat, P., Öksüz, D., & Bottini, R. Distributional predictors of lexical bundle processing: Effects of frequency, association strength, and length.

Öksüz, D., Ge, C., Göymen, D., Rebuschat, P., & Christiansen, M. Chunking ability predicts collocational processing in heritage and non-heritage Turkish speakers.

## Manuscripts under review / revision

Öksüz, D., Akef, S., Mendes, A., & Rebuschat, P. Noun-adjective collocations in L2 Portuguese: Exploring the effects of proficiency and native language in a large-scale learner corpus. [[Open data & code](https://osf.io/7hgsf/overview?view_only=632c04af87ee430b98066733e9fd7626)] [[Preprint](https://osf.io/preprints/psyarxiv/pqw53_v2)]

## Refereed journal articles

Öksüz, D., Alexopoulou, T., Derkach, K., & Tsimpli, I. M. (2025). The influence of L1 typology on the acquisition of the L2 English article: A large-scale corpus study. *Second Language Research*. [Open data & code] [Preprint] [https://doi.org/10.1177/02676583251395876](https://doi.org/10.1177/02676583251395876)

Öksüz, D., Brezina, V., Monaghan, P., & Rebuschat, P. (2024). Individual word and phrase frequency effects in collocational processing: Evidence from typologically different languages, English and Turkish. *Journal of Experimental Psychology: Learning, Memory, and Cognition, 50*(8), 1287–1314. [Open data & code] [https://doi.org/10.1037/xlm0001324](https://doi.org/10.1037/xlm0001324)

Öksüz, D., Brezina, V., & Rebuschat, P. (2021). Collocational processing in L1 and L2: The effects of word frequency, collocational frequency, and association. *Language Learning, 71*, 55–98. [Open data & code] [https://doi.org/10.1111/lang.12427](https://doi.org/10.1111/lang.12427)